blog/urls.py
from django.urls import path

from .views import index, post_detail, about_event, instructors_list, search_posts


app_name = 'blog'

urlpatterns = [
    # path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/<str:query>/', search_posts, name='search_posts'),
    path('instructors/', instructors_list, name='instructors_list'),
    path('news/', about_event, name='news'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', post_detail, name='post_detail'),
    path('', index, name='index'),
]

gallery/urls.py
from django.urls import path

from .views import albums_list, album_detail


app_name = 'gallery'

urlpatterns = [
    path('<str:album_type>/<str:album_name>/', album_detail, name='album_detail'),
    path('video/', albums_list, name='video_albums'),
    path('photo/', albums_list, name='photo_albums'),
]

static_pages/urls.py
from django.urls import path

from .views import static_page


app_name = 'static_pages'

urlpatterns = [
    path('<str:page_name>', static_page, name='static_page')
]

blog/models/category.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Новости'
        verbose_name_plural = 'Новости'

    def __str__(self):
        return self.name

blog/models/comment.py
from django.db import models

from .post import Post


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments', verbose_name='Публикация')
    user_name = models.CharField(max_length=80, verbose_name='Имя пользователя')
    body = models.TextField(max_length=1000, verbose_name='Комментарий')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлено')
    active = models.BooleanField(default=True, verbose_name='Активно')

    class Meta:
        ordering = ('created', )
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return f'Комментарий оставлен пользователем {self.user_name} на пост {self.post}.'

blog/models/instructor.py
from django.db import models

from ckeditor_uploader.fields import RichTextUploadingField


class Instructor(models.Model):
    initials = models.CharField(max_length=100, unique=True, verbose_name='Инициалы')
    contacts = RichTextUploadingField(verbose_name='Подробная информация')
    image = models.ImageField(verbose_name='Фото', blank=True, upload_to='instructors/%Y/%m/%d')

    class Meta:
        verbose_name = 'Инструктор'
        verbose_name_plural = 'Инструкторы'

    def __str__(self):
        return self.initials

blog/models/post.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.urls import reverse

from ckeditor_uploader.fields import RichTextUploadingField

from .category import Category

STATUS_CHOICES = (
    ('draft', 'Черновик'),
    ('published', 'Опубликовано')
)


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    body = RichTextUploadingField(verbose_name='Текст поста')
    publish = models.DateTimeField(default=timezone.now, verbose_name='Опубликовано')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft', verbose_name='Статус')
    image = models.ImageField(upload_to='posts/%Y/%m/%d')

    category = models.ForeignKey(Category, models.PROTECT, verbose_name='Категория')

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms

from captcha.fields import CaptchaField

from .models import Comment


class SearchForm(forms.Form):
    query = forms.CharField(label='')


class CommentForm(forms.ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Comment
        fields = ('user_name', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.views.decorators.cache import cache_page

from .models import Post, Instructor
from .forms import SearchForm, CommentForm
from blog import utils


def search_posts(request, query):
    q_obj = Q(title__icontains=query) | Q(body__icontains=query)
    found_posts = Post.objects.filter(q_obj, status='published')[:10]

    return render(request, 'blog/search.html', {'query': query, 'found_posts': found_posts})


def search_form_actions(request):
    if 'query' in request.GET:
        form = SearchForm(request.GET)

        if form.is_valid():
            query = form.cleaned_data['query']
            return query


def index(request):
    posts = Post.published.all()[:3]
    form = SearchForm()
    query = search_form_actions(request)

    if query:
        return redirect('blog:search_posts', query=query)

    return render(request, 'blog/blog.html', {'posts': posts, 'form': form})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        slug=post,
        status='published',
        publish__year=year,
        publish__month=month,
        publish__day=day
    )

    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(
        request,
        'blog/detail.html',
        {'post': post,
         'comments': comments,
         'new_comment': new_comment,
         'comment_form': comment_form}
    )


def about_event(request):
    page_objs = Post.published.all().order_by('-publish')
    page = utils.get_pagination_page(request, page_objs)

    form = SearchForm()
    query = search_form_actions(request)

    if query:
        return redirect('blog:search_posts', query=query)

    return render(request,
                  'blog/about_event.html',
                  {'page_objs': page.object_list, 'page': page, 'form': form})


@cache_page(15*60)
def instructors_list(request):
    instructors = Instructor.objects.all().order_by('-initials')
    page = utils.get_pagination_page(request, instructors)

    return render(request, 'blog/instructors_list.html', {'instructors': page.object_list, 'page': page})

blog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}Региональная общественная организация "Федерация северной ходьбы в городе Москве"{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">

	<link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<!--[if IE 9]>
		<link rel="stylesheet" href="ie-fix/ie9.css.css">
  	<![endif]-->
  	<!--[if lt IE 9]>
		<link rel="stylesheet" href="ie-fix/ie-none.css.css">
  	<![endif]-->
</head>
<body onclick="deleteImgZoom()">
<!--[if lt IE 7]>

<h1>Обновите браузер</h1>
<![endif]-->

<!-- Шапка начало -->
	<div onclick="openMenu()" style="overflow-x: hidden;"></div>
	<div class="wrapper">
        <p class = "siteName">
			Официальный сайт и блог Региональной общественной организации "Федерация
			северной ходьбы в городе Москве"
		</p>
		<hr align="center" width="100%" size="1px" color="#dddddd" />
		<div class="head">
			<a href="{% url 'blog:index' %}">
                <img class = "head__logo" src="{% static 'img/logo.jpg' %}">
            </a>
			<div class="wrapperMenuAndSearch">
				<div id="head__toggle-btn" onclick="openMenu()">
					<span></span>
					<span></span>
					<span></span>
				</div>
				<nav id = "menu">
					<li>
                        <a class="list__links" href="{% url 'blog:index' %}">Главная</a>
                    </li>

					<li id="aboutFederationPseudo" onclick="openSubMenu('aboutFederationPseudo')">
						<div class="itemsContainer">
							<a section="aboutFederationSection">О федерации</a>
							<span class="triangleDec">▼</span>
						</div>
						<ul class='menu__list'>
                            <li>
                                <a section="aboutFederation" class="list__links" href="{% url 'static_pages:static_page' page_name='goals' %}">Цели</a>
                            </li>
                            <li>
                                <a section="aboutFederation" class="list__links" href="{% url 'static_pages:static_page' page_name='tasks' %}">Задачи</a>
                            </li>
                            <li>
                                <a section="aboutFederation" class="list__links" href="{% url 'static_pages:static_page' page_name='composition' %}">Состав</a>
                            </li>
                            <li>
                                <a section="aboutFederation" class="list__links" href="{% url 'static_pages:static_page' page_name='structure' %}">Структура</a>
                            </li>
                            <li>
                                <a section="aboutFederation" class="list__links" href="{% url 'static_pages:static_page' page_name='founding_documents' %}">Осново пологающие документы</a>
                            </li>
                        </ul>
					</li>

					<li id="sport" onclick="openSubMenu('sport')">
						<div class="itemsContainer">
							<a section="sportSection">Спорт</a>
							<span class="triangleDec">▼</span>
						</div>
						<ul class='menu__list'>
							<li>
                                <a section="sport" class="list__links" href="{% url 'calendar:events_calendar' 7 %}">Календарь соревнований</a>
                            </li>
                            <li>
                                <a section="sport" class="list__links" href="{% url 'calendar:past_competitions' %}">Прошедшие Соревнования</a>
                            </li>
                            <li>
                                <a section="sport" class="list__links" href="{% url 'static_pages:static_page' page_name='protocols' %}">Протоколы</a>
                            </li>
                            <li>
                                <a section="sport" class="list__links" href="{% url 'static_pages:static_page' page_name='judges' %}">Судьи</a>
                            </li>
                            <li>
                                <a section="sport" class="list__links" href="{% url 'static_pages:static_page' page_name='rules' %}">Правила</a>
                            </li>
						</ul>
					</li>

					<li id="news">
                        <a class="list__links" href="{% url 'blog:news' %}">Новости</a>
                    </li>
					<li>
                        <a class="list__links" href="{% url 'blog:instructors_list' %}">Инструкторы</a>
                    </li>
					<li id='gallery' onclick="openSubMenu('gallery')">
						<div class="itemsContainer">
							<a section="gallerySection">Галлерея</a>
							<span class="triangleDec">▼</span>
						</div>
						<ul class='menu__list'>
							<li>
                                <a section="gallery" class="list__links" href="{% url 'gallery:photo_albums' %}">Фото альбомы</a>
                            </li>
                            <li>
                                <a section="gallery" class="list__links" href="{% url 'gallery:video_albums' %}">Видео альбомы</a>
                            </li>
						</ul>
					</li>
					<li>
                        <a class="list__links" href="{% url 'static_pages:static_page' page_name='contacts' %}">Контакты</a>
                    </li>
				</nav>

                <div class="head__searchContainer">
                    {% if form %}
                        <form action="." method="get">
                            {{ form.as_p }}
                            <input type="submit" value="Поиск">
                        </form>
                    {% endif %}
                </div>

                <a class="donateLink" href="{% url 'static_pages:static_page' page_name='donate' %}">
					<div class="box">
						<button class="donateButton">
							<span class="donateButtonTitle">
								Вступить в федерацию
							</span>
						</button>
					</div>
				</a>

			</div>
		</div>
		<hr align="center" width="100%" size="1px" color="#dddddd" />
<!-- Шапка конец -->

        <div class="centralContentAndSidebar">
<!-- Центральный контент начало -->
            {% block content %}
            {% endblock %}
<!-- Центральный контент конец -->
<!-- Cайдбар начало -->
			<div class="sidebarItems">
				<div class="sidebarItems__sidebaritem">
					<a href="http://fst-otm.net/"><img src="{% static '../static/img/fst-otm.net.jpg' %}" alt="baner"></a>
				</div>
				<div class="sidebarItems__sidebaritem">
					<a href="http://www.ruswalk.ru/"><img src="{% static '../static/img/ruswalk.jpg' %}" alt="baner"></a>
				</div>
				<div class="sidebarItems__sidebaritem">
					<a href="https://www.nordicjournal.ru/"><img src="{% static '../static/img/NW.jpg' %}" alt="baner"></a>
				</div>
				<div class="sidebarItems__sidebaritem">
					<a href="https://www.mgpu.ru/?utm_source=yandex&utm_medium=cpc&utm_campaign=43805265&utm_content=7602114356&utm_term=мгпу%20официальный%20сайт&yclid=4921962780622610026"><img src="{% static '../static/img/MGPU.svg' %}" alt="baner"></a>
				</div>
				<div class="sidebarItems__sidebaritem">
					<a href="http://aclive.ru/"><img src="{% static '../static/img/LogoAclive.jpg' %}" alt="baner"></a>
				</div>
			</div>
<!-- Cайдбар конец -->
		</div>

	</div> <!--wrapper конец-->
<!-- Футер начало -->
		<div class="footer">
			<h6 class="footer__heading6"></h6>
			<h3 class="footer__heading3"></h3>
			<p class="footer__paragraph"></p>
			<div class="footer__container">
				<ul class="social">
					<li class="social__item whatsapp">
						<em class="fa fa-whatsapp"></em>
					</li>
					<li class="social__item vk">
						<em class="fa fa-vk"></em>
					</li>
					<li class="social__item twitter">
						<em class="fa fa-twitter"></em>
					</li>
					<li class="social__item instagram">
						<em class="fa fa-instagram"></em>
					</li>
				</ul>
			</div>
		</div>
<!-- Футер конец -->
        <script src="{% static 'js/openMenu.js' %}"></script>
        <script src="{% static 'js/pagination.js' %}"></script>
        <script src="{% static 'js/activeMenuLink.js' %}"></script>
        {% block scripts %}
        {% endblock %}
</body>
</html>