blog/urls.py
from django.urls import path

from .views import index, post_detail, about_event, instructors_list, search_posts


app_name = 'blog'

urlpatterns = [
    # path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/<str:query>/', search_posts, name='search_posts'),
    path('instructors/', instructors_list, name='instructors_list'),
    path('news/', about_event, name='news'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', post_detail, name='post_detail'),
    path('', index, name='index'),
]

events_calendar/urls.py
from django.urls import path

from .views import events_calendar, calendar_event_detail, past_competitions


app_name = 'events_calendar'

urlpatterns = [
    path('past_competitions/', past_competitions, name='past_competitions'),
    path('<int:year>/<int:month>/<int:day>/<int:hour>/<slug:event>/',
         calendar_event_detail, name='calendar_event_detail'),
    path('<int:days>', events_calendar, name='events_calendar'),
]

events_calendar/models/event.py
from django.db import models
from django.db.models import Q
from django.utils import timezone
from django.utils.text import slugify
from django.shortcuts import reverse

from ckeditor_uploader.fields import RichTextUploadingField


def get_date_with_reset_time(date):
    return timezone.datetime(date.year, date.month, date.day)


def get_filter_dates(days):
    return [
        get_date_with_reset_time(timezone.now() + timezone.timedelta(days=x))
        for x in range(days)
    ]


class EventQuerySet(models.QuerySet):
    def days_filtering(self, days):
        q = Q(event_date_from__gte=timezone.now()) | Q(event_date_to__gte=timezone.now())
        events = self.all().filter(q).order_by('event_date_from')

        filter_dates = get_filter_dates(days)
        filtered_events = []

        for event in events:
            if event.event_date_to:
                event_delta_days = (event.event_date_to - event.event_date_from).days

                if event_delta_days > 0:
                    event_dates = (get_date_with_reset_time(event.event_date_from + timezone.timedelta(days=x))
                                   for x in range(event_delta_days))
                else:
                    event_dates = (timezone.datetime(event.event_date_to.year,
                                                     event.event_date_to.month,
                                                     event.event_date_to.day), )
                for event_date in event_dates:
                    if event_date in filter_dates:
                        filtered_events.append(event)
                        break
            else:
                filtered_events.append(event)

        return filtered_events


class EventManager(models.Manager):
    def get_queryset(self):
        return EventQuerySet(self.model, using=self.db)

    def days_filtering(self, days):
        return self.get_queryset().days_filtering(days)


class Event(models.Model):
    title = models.CharField(max_length=150, verbose_name='Название события')
    slug = models.SlugField(max_length=250)
    description = RichTextUploadingField(verbose_name='Описание события')
    event_date_from = models.DateTimeField(verbose_name='Дата события ОТ')
    event_date_to = models.DateTimeField(verbose_name='Дата события ДО', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=timezone.now(), verbose_name='Дата создания события')
    preview_image = models.ImageField(upload_to='events/%Y/%m/%d', verbose_name='Превью картинка')

    objects = models.Manager()
    events = EventManager()

    class Meta:
        verbose_name = 'Соревнование'
        verbose_name_plural = 'Соревнования'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

        super(Event, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('calendar:calendar_event_detail',
                       args=[self.created.year, self.created.month,
                             self.created.day, self.created.hour, self.slug])

    def __str__(self):
        return self.title

events_calendar/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.views.decorators.cache import cache_page
from django.db.models import Q

from blog.utils import get_pagination_page
from .models import Event


def calendar_event_detail(request, year, month, day, hour, event):
    event_obj = get_object_or_404(
        Event,
        slug=event,
        created__year=year,
        created__month=month,
        created__day=day,
        created__hour=hour
    )

    return render(request, 'calendar/event_detail.html', {'event': event_obj})


@cache_page(15*60)
def events_calendar(request, days=7):
    events = Event.events.days_filtering(days)
    page = get_pagination_page(request, events)

    return render(request, 'calendar/events_calendar.html', {'events': page.object_list, 'page': page})


@cache_page(15*60)
def past_competitions(request):
    q = Q(event_date_to__lt=timezone.now()) | Q(event_date_to=None)
    competitions = Event.objects.all().\
        filter(event_date_from__lt=timezone.now()).\
        filter(q).\
        order_by('event_date_from')

    page = get_pagination_page(request, competitions)
    return render(request, 'calendar/past_competitions.html', {'past_competitions': page.object_list, 'page': page})

events_calendar/templates/calendar/event_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ event.title }}
{% endblock %}

{% block content %}
    <div class="containerForCentralContent">
        <div class="ContainerCategoryAndDate">
            <h2 class="ContainerCategoryAndDate__date">
                <strong>
                    {{ event.event_date_from }} {% if event.event_date_to%} - {{ event.event_date_to }}{% endif %}
                </strong>
            </h2>
        </div>
        <div class="ContentDetailPostPage">
            <h1 class="headerDetailPostPage">{{ event.title }}</h1>
            <div class="descriptionContentDetailPostPage">
                {% autoescape off %}
                    <p>{{ event.description }}</p>
                {% endautoescape %}
            </div>
        </div>
    </div>
{% endblock %}

events_calendar/templates/calendar/events_calendar.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Календарь соревнований
{% endblock %}

{% block content %}
    <div class="containerForCentralContent">
        <div class="filterCompetitionsContainer">
            <h3 class="headingH6">Ближайшие события</h3>
            <div class="containerOfFilterEvents">
                <a href="{% url 'events_calendar:events_calendar' 7 %}" class="containerOfFilterEvents__weekEventLink"><input type="button" value="Неделя" class="containerOfFilterEvents__weekEventButton"></a>
                <a href="{% url 'events_calendar:events_calendar' 30 %}" class="containerOfFilterEvents__monthEventLink"><input type="button" value="Месяц" class="containerOfFilterEvents__monthEventButton"></a>
                <a href="{% url 'events_calendar:events_calendar' 90 %}" class="containerOfFilterEvents__3monthEventLink"><input type="button" value="3 Месяца" class="containerOfFilterEvents__3monthEventButton"></a>
                <a href="{% url 'events_calendar:events_calendar' 180 %}" class="containerOfFilterEvents__6monthEventLink"><input type="button" value="6 Месяцев" class="containerOfFilterEvents__6monthEventButton"></a>
                <a href="{% url 'events_calendar:events_calendar' 365 %}" class="containerOfFilterEvents__yearEventLink"><input type="button" value="Год" class="containerOfFilterEvents__yearEventButton"></a>
            </div>
        </div>
         {% if events %}
            {% for event in events %}
                <div class="containerOfEvents">
                    <a href="{{ event.get_absolute_url }}">
                        <img src="{{ event.preview_image.url }}" class = "containerOfEvents__img">
                    </a>
                    <div class="containerOfEvents__description">
                        <p class="containerOfEvents__description__date">
                            <strong>
                                {{ event.event_date_from }} {% if event.event_date_to%} - {{ event.event_date_to }}{% endif %}
                            </strong>
                        </p>
                        <p>
                            <a href="{{ event.get_absolute_url }}" class="containerOfEvents__description__link">{{ event.title }}</a>
                        </p>
                       {% autoescape off %}
                           <div class="containerOfEvents__description__location">
                               {{ event.description|cutimages|cutiframes|truncatewords:30 }}
                           </div>
                       {% endautoescape %}
                    </div>
                    {% if not forloop.last %}
                        <hr align="center" width="100%" size="1px" color="#dddddd" style="margin: 0px 0px 20px 0px;" />
                    {% endif %}
                </div>
            {% endfor %}
        {% endif %}

        {% if page.has_other_pages %}
            {% include 'blog/pagination.html' %}
        {% endif %}
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/truncateCardDescription.min.js' %}"></script>
{% endblock %}

events_calendar/templates/calendar/past_competitions.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Прошедшие соревнования
{% endblock %}

{% block content %}
    <div class="containerForCentralContent">
        {% if past_competitions %}
            {% for past_competition in past_competitions %}
                <div class="containerOfEvents">
                    <a href="{{ past_competition.get_absolute_url }}">
                        <img class="containerOfEvents__img" src="{{ past_competition.preview_image.url }}">
                    </a>
                    <div class="containerOfEvents__description">
                        <p class="containerOfEvents__description__date">
                            <strong>
                                {{ past_competition.event_date_from }} {% if past_competition.event_date_to%} - {{ past_competition.event_date_to }}{% endif %}
                            </strong>
                        </p>
                        <a  class="containerOfEvents__description__link" href="{{ past_competition.get_absolute_url }}">
                            {{ past_competition.title }}
                        </a>
                        {% autoescape off %}
                            <div class="containerOfEvents__description__location">
                                {{ past_competition.description|cutimages|cutiframes|truncatewords:50 }}
                            </div>
                        {% endautoescape %}
                    </div>
                    {% if not forloop.last %}
                        <hr align="center" width="100%" size="1px" color="#dddddd" style="margin: 0px 0px 20px 0px;" />
                    {% endif %}
                </div>
            {% endfor %}
        {% endif %}

        {% if page.has_other_pages %}
            {% include 'blog/pagination.html' %}
        {% endif %}
    </div>

{% endblock %}

{% block scripts %}
    <script src="{% static 'js/truncateCardDescription.min.js' %}"></script>
{% endblock %}